### PR TITLE
Fix Makefile.PL and CI after script-branch split

### LINKED ISSUE #366: CI is broken with recent changes
The recent changes to branch `2.0` introduced some regressions view https://github.com/Test-More/Test2-Harness/actions/runs/24826342121/job/72663174835
```
Run perl Makefile.PL
Illegal or missing directory 'share' at /usr/local/share/perl/5.38.2/File/ShareDir/Install.pm line 105.
	File::ShareDir::Install::_add_dir(HASH(0x561d2631f538), "share") called at /usr/local/share/perl/5.38.2/File/ShareDir/Install.pm line 42
	File::ShareDir::Install::install_share("dist") called at Makefile.PL line 28
````

Let's understand and fix that issue

### PR DESCRIPTION
**Pull request by atoomic**
## Summary

Fixes #366. Collects the set of build, CI, and test-side fixes needed
to make the full CI matrix and local `dzil` / `make test` workflows
green on the 2.0 branch, without touching in-flight rewrite work
(App::Yath2::Command → role migration, App::Yath2::IPC port,
App::Yath2UI::* port).

## What changed

**Build and packaging**
- `Makefile.PL` / `dist.ini` / `cpanfile` brought in line with the
  post-script-branch-split layout; stale `scripts/yath` dropped,
  `App::Yath::Script >= 2.000011` declared as a prereq, and
  `Long::Jump`, `Object::HashBase`, `mro` added where dist.ini already
  required them but the generated files had drifted.
- GitHub Actions workflow installs `App::Yath::Script` from the
  `script` branch before `perl Makefile.PL`.
- `share/` retained as an empty directory with `.gitkeep` so
  `install_share()` has a target.
- `test.pl` walks `t/` with `File::Find` and passes `.t` files
  positionally, matching the rewritten `Command::test`.
- `dist.ini` excludes leftover `Test2-Harness2-<ver>/` build
  directories from `GatherDir` so consecutive `dzil build` runs stop
  flapping on the regenerated `cpanfile`.
- `release-scripts/generate_{command,options}_pod.pl` tolerate
  compile failures from in-flight command modules by warning and
  emitting stub POD instead of aborting the build.

**Runtime / CLI**
- `App::Yath2::do_start` now surfaces the real command-load error
  when `App::Yath2::Command::<cmd>` fails to compile, instead of
  falling through to the generic "no command" path.
- `Command::test` prints per-failure diagnostics on job failure so
  CI is actionable. The dump is gated behind `$ENV{CI}` or
  `YATH_TEST_VERBOSE=1` per review feedback, so local developer runs
  stay quiet.

**AI tests (`t/AI/`)**
- Logger tests updated to match the lazy-resolution design: the
  JSON/JSONL loggers compute `output_file` from identity attributes
  via `output_file_basename` at write time, not at construction. The
  real invariant is asserted (`output_files()` croaks with `/logdir/`
  when neither `output_file` nor `logdir` is available).
- Run-service integration test adopts the
  `logs/runs/<run_id>.jsonl` layout introduced by commit `854757360`
  ("Loggers: derive output paths from identity attrs; interpose
  run-service collector").
- Run-service test tolerates the `finish()` / service-exit peer-gone
  race on Linux CI without masking real failures: only
  `/peer .* went away/` is swallowed, and `terminate_on_destroy` is
  cleared to avoid DESTROY re-racing.
- Lifecycle test accepts zombie PIDs as reaped via a `proc_gone()`
  helper (checks `/proc/<pid>/status` on Linux for `State: Z`).
  GitHub matrix jobs run in containers whose PID 1 is not tini, so
  detached services sent SIGTERM linger as zombies and plain
  `kill 0` never flips — this fix targets that specific case.
- Collector `burst_sync` test adds 10ms pacing between writer steps
  to preserve same-pipe FIFO ordering under scheduler pressure.
- `Test::Loggers::classic_test_loggers` fix substitutes `%LOG_DIR%`
  at instantiation time to stop leaking the placeholder directory
  into the repo root.

## Verification

- `dzil build` runs cleanly and is stable across consecutive
  invocations (no flapping on `cpanfile`).
- `perl Makefile.PL && make && make test` passes locally.
- GitHub Actions "simple testrun" (host-native) and "linux Perl 5.*"
  (containerized) matrix jobs are both green.

## Out of scope (intentionally not in this PR)

- Completing the `App::Yath2::Command` class → `App::Yath2::Role::Command`
  role migration for the remaining commands.
- Porting `App::Yath2::IPC`, `App::Yath2UI::Server`, and
  `App::Yath2UI::Schema::*` modules from `reference/old2/`.
- Adding `render_status_data` to `Test2::Harness2::Util`'s exports.
- Source-side fix for `Spawn::finish` peer-gone race (currently
  handled test-side).
- Deeper look at Atomic::Pipe `mixed_data_mode` same-pipe FIFO
  guarantees when a real producer emits line+message back-to-back.

### CODE REVIEW

File: lib/App/Yath2/Command/test.pm [hunk 1]
```diff
@@ -111,14 +115,147 @@ sub _aggregate_pass {
...
-    return $all_pass;
+    return ($all_pass, \@failures);
+}
+
+# Diagnostic-only: on any failing job, print the test file, exit status,
+# failing assertions, and STDERR/DIAG lines captured in the per-test
+# JSONL log. The minimal test command otherwise writes only machine
+# logs, which makes CI failures opaque ("yath exited with 256" with no
+# test context). This turns the failure into actionable output.
+sub _print_failure_details {
```
Comment (atoomic) [inline lib/App/Yath2/Command/test.pm]: This is only useful on CI / local development, let's make sure it s disabled by default and only enabled on CI or when using an ENV variable

File: lib/App/Yath2/Command/test.pm [hunk 2]
```diff
@@ -81,13 +81,16 @@ sub run {
...
-    my $pass = $self->_aggregate_pass($harness_log);
+    my ($pass, $failures) = $self->_aggregate_pass($harness_log);
 
     $settings->workspace->create_option(keep_dirs => 1);
 
     print "Work directory: $workdir\n";
     print "Harness log:    $harness_log\n";
 
+    $self->_print_failure_details($logdir, $failures)
+        if !$pass && $failures && @$failures;
```
Comment (atoomic) [inline lib/App/Yath2/Command/test.pm]: only for debugging purpose should not be by default

**Comment by atoomic** [comment]
Out-of-scope follow-ups from this PR have been filed as separate issues, labeled `PTS26`:

- #385 — Complete `App::Yath2::Command` → `App::Yath2::Role::Command` migration for the remaining 21 commands.
- #386 — Port `App::Yath2::IPC` and `App::Yath2UI::{Server,Schema::*}` from `reference/old2/`.
- #387 — Export `render_status_data` from `Test2::Harness2::Util`.
- #388 — Source-side fix for the `Spawn::finish` peer-gone race (currently handled test-side).
- #389 — Clarify `Atomic::Pipe` `mixed_data_mode` same-pipe FIFO guarantees.

**Comment by atoomic** [comment]
Follow-up per review feedback: the silent `finish()` peer-gone swallow in `t/AI/integration/harness2_run_service.t` is now a visible `# TODO` (see commit `4e1992b6a`). Tracker: #391 (paired with the source-side fix in #388).

**Comment by atoomic** [comment]
Another PTS26 follow-up filed while validating `make test` locally: #392 -- hardcoded 10s run-service readiness timeout aborts local dev on macOS. This is what makes local `make test` fail on this branch (CI unaffected, containers hit the ready signal in <1s). Not a regression from #384; predates it.
